############################################################################
# Contest 2026 team 458 WristClaw agent - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = wristclaw
PRIORITY  = $(CONFIG_WRISTCLAW_PRIORITY)
STACKSIZE = $(CONFIG_WRISTCLAW_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_458_WRISTCLAW)

MAINSRC = wristclaw_main.c wc_agent.c wc_proto.c wc_ui.c

include $(APPDIR)/Application.mk
